/*    ______      _
 *   / ____/___ _(_)___ ___  ____ _____
 *  / / __/ __ `/ / __ `__ \/ __ `/ __ \
 * / /_/ / /_/ / / / / / / / /_/ / / / /
 * \____/\__,_/_/_/ /_/ /_/\__,_/_/ /_/
 *
 * Storytelling Text Based Game Engine
 * This file is PEG grammar for Gaiman programming language
 *
 * Copyrigth (C) 2021 Jakub T. Jankiewicz <https://jcubic.pl/me>
 *
 * Released under GNU GPL v3 or later
 */
{

    var heredoc_begin = null;
    var $$__m; // result of match
    var variable_prefix = '$_';
    var match_identifer = make_identifier('$$__m');
    var match_method = make_identifier('match');

    function make_if(test, body, alternative) {
        return {
            "type": "IfStatement",
            "test": test,
            "consequent": make_block(body),
            "alternate": alternative
        };
    }
    function iife(body) {
        const result = expression_statement({
            "type": "CallExpression",
            "callee": {
                "type": "FunctionExpression",
                "id": null,
                "async": true,
                "params": [],
                "body": make_block(body)
            },
            "arguments": []
        });
        return result;
    }
    function method(...props) {
        return property(...props.map(make_identifier));
    }
    function gaiman_prop(method) {
        return property(make_identifier("gaiman"), make_identifier(method));
    }
    function gaiman_call(method, ...args) {
        return call(gaiman_prop(method), ...args);
    }
    function map_extra_method(method) {
        return method.replace(/\*$/, '_extra')
    }
    function make_block(body) {
        return {
            "type": "BlockStatement",
            "body": body
        }
    }
    function make_identifier(name) {
        return {
            type: 'Identifier',
            name: name
        };
    }
    function make_var_declaration(identifier, init) {
        return {
            type: "VariableDeclarator",
            id: make_identifier(identifier),
            init: init
        };
    }
    function make_vars(kind, ...declarations) {
        return {
            type: "VariableDeclaration",
            kind: kind,
            declarations: declarations
        };
    }
    function variable(name, expression) {
        return {
            "type": "VariableDeclaration",
            "declarations": [{
                "type": "VariableDeclarator",
                "id": name,
                "init": expression
            }],
            "kind": "let"
        };
    } 
    var for_loop = with_loop_guard(function(variable, value, body) {
        if (variable instanceof Array) {
            return {
                "type": "ForOfStatement",
                "await": false,
                "left": {
                    "type": "VariableDeclaration",
                    "declarations": [{
                        "type": "VariableDeclarator",
                        "id": {
                            "type": "ArrayPattern",
                            "elements": variable
                        },
                        "init": null
                     }],
                     "kind": "let"
                },
                "right": call(method('Object', 'entries'), value),
                "body": {
                    "type": "BlockStatement",
                    "body": body
                }
            };
        }
        return {
            "type": "ForOfStatement",
            "await": false,
            "left": {
                "type": "VariableDeclaration",
                "declarations": [{
                    "type": "VariableDeclarator",
                    "id": variable,
                    "init": null
                }],
                "kind": "let"
            },
            "right": value,
            "body": {
                "type": "BlockStatement",
                "body": body
            }
        };
    });
    var while_loop = with_loop_guard(function(test, body) {
        return {
            "type": "WhileStatement",
            "test": test,
            "body": {
                "type": "BlockStatement",
                "body": body
            }
        };
    });
    function literal(value) {
        return { type: 'Literal', value }
    }
    function expression_statement(expression) {
        return {
            "type": "ExpressionStatement",
            "expression": expression
        };
    }
    let loop_count = 0;
    function with_loop_guard(fn) {
        var guard_var = make_identifier('loop_guard');
        var cond = {
            "type": "UnaryExpression",
            "operator": "!",
            "argument": {
                "type": "UpdateExpression",
                "operator": "--",
                "argument": guard_var,
                "prefix": true
            },
            "prefix": true
        };
        return function(...args) {
            const last = args.length - 1;
            const body = args[last];
            args[last] = [
                make_if(gaiman_call('should_break_loop', literal(++loop_count)), [
                     jump('break')
                ]),
                ...body
            ];
            return [
                fn(...args),
                expression_statement(gaiman_call('exit_loop', literal(loop_count)))
            ];
        };
    }
    function expression_fold(type) {
        return function fold(head, tail, mapping) {
             return tail.reduce(function(result, element) {
                var opertator = mapping ? mapping[element[1]] : element[1];
                return {
                    "type": type,
                    "operator": opertator,
                    "left": result,
                    "right": element[3]
                };
            }, head);
        }
    }
    var binary_fold = expression_fold("BinaryExpression");
    var logical_fold = expression_fold("LogicalExpression");
    function property(...args) {
        return args.reduce(function(result, item) {
            return {
                type: "MemberExpression",
                computed: false,
                object: result,
                property: item
            };
        });
    }
    function call(callee, ...args) {
        return {
            type: "CallExpression",
            callee: callee,
            arguments: args
        };
    }
    function create_template_literal(string) {
        var re = /(\$[A-Z_$a-z][A-Z_a-z0-9]*)/;
        var expressions = [];
        var constants = [];
        string.split(re).map(token => {
            if (token.match(re)) {
                expressions.push(make_identifier(token.replace(/^\$/, '$_')));
            } else {
                constants.push({
                    "type": "TemplateElement",
                    "value": {
                        "raw": token
                    }
                });
            }
        });
        return {
            type: "TemplateLiteral",
            expressions,
            quasis: constants
        };
    }
    function try_catch(body) {
        return {
            "type": "TryStatement",
            "block": {
                "type": "BlockStatement",
                body: body
            },
            "handler": {
                "type": "CatchClause",
                "param": {
                    "type": "Identifier",
                    "name": "e"
                },
                "body": {
                    "type": "BlockStatement",
                    "body": [{
                        "type": "ExpressionStatement",
                          "expression": gaiman_call('error', make_identifier("e"))
                    }]
                }
            }
        };
    }
    function jump(name) {
        const mapping = {
            "break": "BreakStatement",
            "continue": "ContinueStatement"
        };
        return {
            "type": mapping[name],
            "label": null
        };
    }
    // move error location without mutation
    function move_location(loc, start, end) {
        const { start: loc_start, end: loc_end } = loc;
        const new_loc = {
            ...loc,
            start: {
                ...loc_start,
                column: loc_start.column + start,
                offset: loc_start.offset + start
            },
            end: {
                ...loc_end,
                column: loc_end.column + end,
                offset: loc_end.offset + end
            }
        };
        return new_loc;
    }
    var async_commands = ["ask", "get", "post", "sleep", "sleep*", "echo*", "prompt*", "input*", "ask*"];
    var sync_commands = ["echo", "prompt", "config", "input", "parse*", "parse", "store"];
    var available_commands = async_commands.concat(sync_commands);
}

Start = statements:statements {
    return {
        "type": "Program",
        "body": [
            iife([
                try_catch(statements)
            ])
        ]
    };
}

statements = statements:(!"end" _ statement* / _) {
    return statements[2].flat(2).filter(Boolean);
}

statement = !"end" _ statement:(if / for_loop / while_loop / jump / return / var / expression_statement / function_definition) _ {
   return statement;
}

expression_statement = !keyword expression:expression_like {
    return  {
      "type": "ExpressionStatement",
      "expression": expression
    };
}

expression_like = set / command / expression / function_call


expression = heredoc / function_call / property / math_expression / bracket_prop_access / dict / match_var / array / any_name / string / literal

command = adapter_command / match

end = "end" { return null; }

if = _ "if" _ cond:expression_like _ "then" _ body:statements next:(end / if_next / last_else) _ {
  return make_if(cond, body, next);
}

if_next = _ "else" _ if_next:if {
    return if_next;
}

last_else = _ "else" _ body:statements "end" {
    return {
        "type": "BlockStatement",
        "body": body
    };
}

jump = _ keyword:$("break" / "continue") _ {
    return jump(keyword);
}

for_loop = "for" SP !keyword arg:((variable _ "," _ variable) / variable) SP "in" SP iterator:(expression_like / variable) _ "do" _ body:statement* _ "end" _ {
    if (arg instanceof Array) {
        return for_loop([arg[0], arg[4]], iterator, body);
    } else {
        return for_loop(arg, iterator, body);
    }
}

while_loop = "while" SP test:expression _ "do" _ body:statements _ "end" _ {
    return while_loop(test, body);
}

array = "[" values:((expression_like / variable) _ ","? _)* "]" {
    return {
        "type": "ArrayExpression",
        "elements": values.map(value => value[0])
    };
}

bracket_prop_access = object:any_name props:("[" _ property:(math_expression / dict / match_var / array / function_call / string / literal) _ "]")+ _ {
    props = props.map(prop => prop[2]);
    return props.reduce((object, property) => {
        return {
            type: 'MemberExpression',
            computed: true,
            object,
            property
        };
    }, object);
}


dict_prop = _ name:string _ "=>" _ value:expression _ {
    return {
        type: "Property",
        key: name,
        computed: true,
        value,
        kind: "init",
        method: false,
        shorthand: false
    };
}

dict_list = _ first:dict_prop rest:(_ "," _ dict_prop _)* _ {
    const list = rest.map(prop => prop[3]);
    list.unshift(first);
    return list;
}

dict = _ "{" _ properties:dict_list? _ "}" _ {
    return {
        "type": "ObjectExpression",
        "properties": properties || []
    };
}

// TODO: make "," mandatory as in dict

function_call = _ !keyword name:(property / variable) _ "(" names:((expression_like / variable) _ ","? _)* ")" _ {
    return {
        "type": "AwaitExpression",
        "argument": call(name, ...names.map(name => name[0]))
    };
}

function_definition = _ "def" _ name:variable _ "(" args:(variable _ ","? _)* ")" _  body:statement* _ "end" _ {
    const fn_name = name.name.replace(/\$_/, '');
    if (available_commands.includes(fn_name)) {
        const error = new Error(`invalid function name, '${fn_name}' is a command`);
        error.location = move_location(location(), 4, fn_name.length + 4);
        throw error;
    }
    var args = args.map(function(arg) { return arg[0]; });
    return {
        "type": "FunctionDeclaration",
        "id": name,
        "params": args,
        "async": true,
        "body": {
            "type": "BlockStatement",
            "body": body
        }
    };
}

return = _ "return" _ expression:expression_like _ {
    return {
        "type": "ReturnStatement",
        "argument": expression
    };
}

var = _ "let" _ name:(variable) _ "=" _ expression:expression_like _ {
    return {
        "type": "VariableDeclaration",
        "declarations": [{
            "type": "VariableDeclarator",
            "id": name,
            "init": expression
        }],
        "kind": "let"
    };
}

string = "\"" ([^"] / "\\\\\"")*  "\"" { // "
    var string = text().replace(/\\n/g, '\uFFFF\uFFFF').replace(/\n/g, '\\n');
    string = JSON.parse(string).replace(/\uFFFF\uFFFF/g, '\\n');
    return create_template_literal(string);
}

literal = value:(integer / boolean / null) {
   return {"type": "Literal", "value": value };
}

boolean = value:("true" / "false") {
    return value === "true";
}

null = "null" { return null; }

infinity = "infinity" {
    return make_identifier('Infinity');
}

asterisk_name = word:$([a-z]+ "*") { return word; }

command_name = word:$([a-z]+ "*"?) { return word; }

async_command_name = word:$[a-z]+ { return word; }

adapter_async_strings = word:async_command_name &{ return async_commands.includes(word) } { return word; }

adapter_asterisk_strings = word:asterisk_name &{ return async_commands.includes(word) } { return word; }

adapter_static_strings = word:command_name &{ return sync_commands.includes(word); } { return word; }

adapter_command = extra_commands / async_command / static_command

extra_commands = _ method:adapter_asterisk_strings _ expr:(adapter_command / expression) _ args:(
    ("," _ expression)+ / '' {
      error(`Command ${method} require at least two arguments`);
    }) _ {
    return  {
        "type": "AwaitExpression",
        "argument": gaiman_call(map_extra_method(method), expr, ...args.map(x => x[2]))
    };
}


async_command = _ method:adapter_async_strings " " _ expr:(adapter_command / expression) _ args:("," _ expression _)* {
    return  {
        "type": "AwaitExpression",
        "argument": gaiman_call(method, expr, ...args.map(x => x[2]))
    };
}

static_command = _ method:adapter_static_strings _ expr:(adapter_command / expression) _ args:("," _ expression)* {
    return gaiman_call(map_extra_method(method), expr, ...args.map(x => x[2]));
}

match = expression:(match_var / property / variable) _ "=~" _ re:re _ {
    return {
        type: "AssignmentExpression",
        operator: "=",
        left: match_identifer,
        right: call(property(call(make_identifier('String'), expression), match_method), re)
    };
}

object = _ "{" _ props:(object_prop ","?)* _ "}" {
   var props =  props.map(function(prop) { return prop[0]; });
   return {"properties": props}
}

object_prop = _ prop:name _ ":" _ value:expression _  {
  return { prop: prop, value: value };
}

re = "/" re:([^/] / "\\\\/")* "/" flags:[igsu]* {
    return {
        type: "Literal",
        value: {},
        regex: {
            pattern: re.join(''),
            flags: flags ? flags.join('') : ''
        }
    }
}
property = struct:variable rest:("." name)+ {
    rest = rest.map(arg => arg[1]);
    return property(struct, ...rest.map(make_identifier));
}

math_expression = unary / or


not = "not" " " { return "!"; }

unary = op:("-" / "+" / not) _ expression:or {
    return {
        "type": "UnaryExpression",
        "operator": op,
        "argument": expression
    };
}

or
  = head:and tail:(SP "or" SP and)* {
      return logical_fold(head, tail, {"or": "||"});
  }

and
  = head:equal tail:(SP "and" SP equal)* {
      return logical_fold(head, tail, {"and": "&&"});
  }

equal
  = head:binary tail:(_ ("==" / "!=") _ binary)* {
      return binary_fold(head, tail, {"==": "===", "!=": "!=="});
    }

binary
  = head:plus_minus tail:(_ ("<=" / ">=" / "<" / ">") _ plus_minus)* {
      return binary_fold(head, tail);
    }

plus_minus
  = head:mul_div tail:(_ ("+" / "-") _ mul_div)* {
      return binary_fold(head, tail);
    }

mul_div
  = head:factor tail:(_ ("*" / "/" / "%") _ factor)* {
      return binary_fold(head, tail);
    }

factor
  = "(" _ expr:(math_expression / adapter_command) _ ")" { return expr; }
  / bracket_prop_access / function_call / string / literal / match_var / variable / infinity

any_name = variable:name {
  return make_identifier(variable_prefix + variable);
}

scoped = !keyword variable:name &{ return !available_commands.includes(variable) } {
  return make_identifier(variable_prefix + variable);
}

global = !keyword variable:("cookie" / "location" / "argv" / "node") {
    return make_identifier(variable);
}

variable = global / scoped

set = set_cookie / set_local

set_cookie = "cookie." name:name _ "=" _ expr:expression {
    return {
        "type": "AssignmentExpression",
        "operator": "=",
        "left": property(
            make_identifier('document'),
            make_identifier('cookie')
        ),
        "right": {
            "type": "BinaryExpression",
            "operator": "+",
            "left": {
                "type": "Literal",
                "value": name + "="
            },
            "right": call(make_identifier('String'), expr)
        }
    };
}

assign_operator = $("=" !"=" / "*=" / "+=" / "-=" / "%=" / "/=")


set_local = left:(bracket_prop_access / property / scoped) _ operator:assign_operator _  right:(expression_like / variable) {
    return {
        "type": "AssignmentExpression",
        "operator": operator,
        "left": left,
        "right": right
    };
}

match_var = "$" num:integer {
    return {
        type: "MemberExpression",
        computed: true,
        object: match_identifer,
        property: {
            type: "Literal",
            value: num
        }
    };
}

heredoc = "<<<" beginMarker "\n" text:content endMarker {
    const loc = location();
    const min = loc.start.column - 1;
    const re = new RegExp(`^ {${min}}`, 'mg');
    return {
        type: 'Literal',
        value: text.replace(re, '')
    };
}

__ = (!"\n" !" " .)

marker 'Marker' = $__+

beginMarker = m:marker { heredoc_begin = m; }

endMarker = "\n" " "* end:marker &{ return heredoc_begin === end; }

content = $(!endMarker .)*

comment = "#" [^\n]* { return null; }

integer = [0-9]+ { return parseInt(text(), 10); }

keyword = "if" / "then" / "end" / "else" / "return" / "def" / "do" / "in" / "for" / "while" / "break" / "continue"

name = [A-Z_$a-z][A-Z_a-z0-9]* { return text(); }

WP = [ \t\n\r]

_ "optional whitespace"
  = WP* comment / WP* { return []; }

SP "whitespace"
  = WP+
