/*    ______      _
 *   / ____/___ _(_)___ ___  ____ _____
 *  / / __/ __ `/ / __ `__ \/ __ `/ __ \
 * / /_/ / /_/ / / / / / / / /_/ / / / /
 * \____/\__,_/_/_/ /_/ /_/\__,_/_/ /_/
 *
 * Storytelling Text Based Game Engine
 * This file is PEG grammar for Gaiman programming language
 *
 * Copyrigth (C) 2021 Jakub T. Jankiewicz <https://jcubic.pl/me>
 *
 * Released under GNU GPL v3 or later
 */
{

    var heredoc_begin = null;
    var $$__m; // result of match
    var variable_prefix = '$_';
    var match_identifer = make_identifier('$$__m');
    var match_method = make_identifier('match');

    function make_if(test, body, alternative) {
        return {
            "type": "IfStatement",
            "test": test,
            "consequent": make_block(body),
            "alternate": alternative
        };
    }
    function main(body) {
        const result = {
            "type": "FunctionDeclaration",
            "id": make_identifier('main'),
            "params": [],
            "body": make_block(body),
            "generator": false,
            "expression": false,
            "async": true
        };
        return result;
    }
    function build_list(first, rest) {
        const list = rest.map(prop => prop[3]);
        list.unshift(first);
        return list;
    }
    function method(...props) {
        return property(...props.map(make_identifier));
    }
    function gaiman_prop(method) {
        return property(make_identifier("gaiman"), make_identifier(method));
    }
    function gaiman_call(method, ...args) {
        return call(gaiman_prop(method), ...args);
    }
    function map_extra_method(method) {
        return method.replace(/\*$/, '_extra')
    }
    function make_block(body) {
        return {
            "type": "BlockStatement",
            "body": body
        }
    }
    function make_identifier(name) {
        return {
            type: 'Identifier',
            name: name
        };
    }
    function make_var_declaration(identifier, init) {
        return {
            type: "VariableDeclarator",
            id: make_identifier(identifier),
            init: init
        };
    }
    function make_vars(kind, ...declarations) {
        return {
            type: "VariableDeclaration",
            kind: kind,
            declarations: declarations
        };
    }
    function variable(name, expression) {
        return {
            "type": "VariableDeclaration",
            "declarations": [{
                "type": "VariableDeclarator",
                "id": name,
                "init": expression
            }],
            "kind": "let"
        };
    }
    var for_loop = with_loop_guard(function(variable, value, body) {
        if (variable instanceof Array) {
            return {
                "type": "ForOfStatement",
                "await": false,
                "left": {
                    "type": "VariableDeclaration",
                    "declarations": [{
                        "type": "VariableDeclarator",
                        "id": {
                            "type": "ArrayPattern",
                            "elements": variable
                        },
                        "init": null
                     }],
                     "kind": "let"
                },
                "right": call(method('Object', 'entries'), value),
                "body": make_block(body)
            };
        }
        return {
            "type": "ForOfStatement",
            "await": false,
            "left": {
                "type": "VariableDeclaration",
                "declarations": [{
                    "type": "VariableDeclarator",
                    "id": variable,
                    "init": null
                }],
                "kind": "let"
            },
            "right": value,
            "body": make_block(body)
        };
    });
    var while_loop = with_loop_guard(function(test, body) {
        return {
            "type": "WhileStatement",
            "test": test,
            "body": make_block(body)
        };
    });
    function literal(value) {
        return { type: 'Literal', value }
    }
    function expression_statement(expression) {
        return {
            "type": "ExpressionStatement",
            "expression": expression
        };
    }
    let loop_count = 0;
    function with_loop_guard(fn) {
        var guard_var = make_identifier('loop_guard');
        var cond = {
            "type": "UnaryExpression",
            "operator": "!",
            "argument": {
                "type": "UpdateExpression",
                "operator": "--",
                "argument": guard_var,
                "prefix": true
            },
            "prefix": true
        };
        return function(...args) {
            const last = args.length - 1;
            const body = args[last];
            args[last] = [
                make_if(gaiman_call('should_break_loop', literal(++loop_count)), [
                     jump('break')
                ]),
                ...body
            ];
            return [
                fn(...args),
                expression_statement(gaiman_call('exit_loop', literal(loop_count)))
            ];
        };
    }
    function expression_fold(type) {
        return function fold(head, tail, mapping) {
             return tail.reduce(function(result, element) {
                var opertator = mapping ? mapping[element[1]] : element[1];
                return {
                    "type": type,
                    "operator": opertator,
                    "left": result,
                    "right": element[3]
                };
            }, head);
        }
    }
    var binary_fold = expression_fold("BinaryExpression");
    var logical_fold = expression_fold("LogicalExpression");
    function property(...args) {
        return args.reduce(function(result, item) {
            return {
                type: "MemberExpression",
                computed: false,
                object: result,
                property: item
            };
        });
    }
    function call(callee, ...args) {
        return {
            type: "CallExpression",
            callee: callee,
            arguments: args
        };
    }
    function parse_string(string) {
        var result = string.replace(/\\n/g, '\uFFFF\uFFFF');
        result = JSON.parse(result);
        result = result.replace(/\\/g, '\\\\').replace(/\uFFFF\uFFFF/g, '\\n');
        return result;
    }
    function create_template_literal(string) {
        var re = /(\$[A-Z_$a-z][A-Z_a-z0-9]*)/;
        var expressions = [];
        var constants = [];
        string.split(re).map(token => {
            if (token.match(re)) {
                expressions.push(make_identifier(token.replace(/^\$/, '$_')));
            } else {
                constants.push({
                    "type": "TemplateElement",
                    "value": {
                        "raw": escape_quote(token)
                    }
                });
            }
        });
        return {
            type: "TemplateLiteral",
            expressions,
            quasis: constants
        };
    }
    function bang_bang(argument) {
        return {
            "type": "UnaryExpression",
            "operator": "!",
            "argument": {
                "type": "UnaryExpression",
                "operator": "!",
                "argument": argument,
                "prefix": true
            },
            "prefix": true
        };
    }
    function escape_quote(str) {
       return str.replace(/\$\x7b/g, '\\$\x7b');
    }
    function try_catch(body) {
        return {
            "type": "TryStatement",
            "block": make_block(body),
            "handler": {
                "type": "CatchClause",
                "param": {
                    "type": "Identifier",
                    "name": "e"
                },
                "body": {
                    "type": "BlockStatement",
                    "body": [{
                        "type": "ExpressionStatement",
                          "expression": gaiman_call('error', make_identifier("e"))
                    }]
                }
            }
        };
    }
    function jump(name) {
        const mapping = {
            "break": "BreakStatement",
            "continue": "ContinueStatement"
        };
        return {
            "type": mapping[name],
            "label": null
        };
    }
    function lambda(params, body) {
        return {
            "type": "FunctionExpression",
            "id": make_identifier('lambda'),
            "async": true,
            "params": params,
            "body": make_block(body)
        };
    }
    // move error location without mutation
    function move_location(loc, start, end) {
        const { start: loc_start, end: loc_end } = loc;
        const new_loc = {
            ...loc,
            start: {
                ...loc_start,
                column: loc_start.column + start,
                offset: loc_start.offset + start
            },
            end: {
                ...loc_end,
                column: loc_end.column + end,
                offset: loc_end.offset + end
            }
        };
        return new_loc;
    }
    function is_number_literal(obj) {
        if (!obj || obj instanceof Array) {
            return false;
        }
        return typeof obj === 'object' &&
            obj.type === 'Literal' &&
            typeof obj.value === 'number';
    }
    var async_commands = ["ask", "get", "post", "sleep", "echo*", "prompt*", "input*", "ask*", "post*"];
    var sync_commands = ["echo", "type", "prompt", "config", "input", "parse*", "parse", "store", "complete", "update"];
    var available_commands = async_commands.concat(sync_commands);
    var extra_single = ["sleep*", "get*"];
    var blacklist_properties = ["constructor", "__proto__", "prototype"];
}

Start = statements:statements {
    return {
        "type": "Program",
        "body": [
            main([
                try_catch(statements)
            ])
        ]
    };
}

statement_list = !"end" _ statements:statement* _ {
    return statements.flat(2).filter(Boolean);
}

statements = statement_list / null_array

statement = !"end" _ statement:(if / for_loop / while_loop / jump / return / var / expression_statement / function_definition) _ {
   return statement;
}

expression_statement = !keyword expression:expression_like {
    return  {
      "type": "ExpressionStatement",
      "expression": expression
    };
}

expression_like = set / command / expression


expression = math_expression / heredoc / function_call / lambda / prop_access / dict / match_var / array / any_name / string / literal

command = adapter_command / match

end = "end" { return null; }

if = _ "if" _ cond:expression_like _ "then" _ body:statements next:(end / if_next / last_else) _ {
  return make_if(cond, body, next);
}

if_next = _ "else" _ if_next:if {
    return if_next;
}

last_else = _ "else" _ body:statements "end" {
    return {
        "type": "BlockStatement",
        "body": body
    };
}

jump = _ keyword:$("break" / "continue") _ {
    return jump(keyword);
}

for_loop = "for" SP !keyword arg:((variable _ "," _ variable) / variable) SP "in" SP iterator:(expression_like / variable) _ "do" _ body:statements _ "end" _ {
    if (arg instanceof Array) {
        return for_loop([arg[0], arg[4]], iterator, body);
    } else {
        return for_loop(arg, iterator, body);
    }
}

while_loop = "while" SP test:expression _ "do" _ body:statements _ "end" _ {
    return while_loop(test, body);
}

bracket_prop = prop:("[" _ property:(math_expression / dict / match_var / array / function_call / string / literal) _ "]")

dot_prop = prop:(_ "." _ name) {
    return make_identifier(prop[3]);
}

prop_access = object:(global / array / string / any_name) props:(bracket_prop / dot_prop)+ _ {
    return props.reduce((object, property) => {
        const result = {
            type: 'MemberExpression',
            object,
            property
        };
        if (property[0] == "[") {
            result.computed = true
            result.property = property[2];
        }
        return result;
    }, object);
}

dict_prop = _ name:string _ "=>" _ value:expression _ {
    return {
        type: "Property",
        key: name,
        computed: true,
        value,
        kind: "init",
        method: false,
        shorthand: false
    };
}

param_list = first:variable rest:(_ "," _ variable _)* _ {
    return build_list(first, rest);
}

argument = expression_like / variable

argument_list = first:argument rest:(_ "," _ argument _)* _ {
    return build_list(first, rest);
}

array = "[" values:(argument_list / null_array) "]" {
    return {
        "type": "ArrayExpression",
        "elements": values
    };
}

dict_list = _ first:dict_prop rest:(_ "," _ dict_prop _)* _ {
    return build_list(first, rest);
}

dict = _ "{" _ properties:(dict_list / null_array)  _ "}" _ {
    return {
        "type": "ObjectExpression",
        "properties": properties
    };
}

lambda_value = "(" _ lambda:lambda _ ")" { return lambda; }

call = "(" args:(argument_list / null_array) ")"


function_call = _ !keyword expression:(prop_access / lambda_value / variable) _ "(" args:(argument_list / null_array) ")" _ rest:(call / bracket_prop / dot_prop)* {
    if (rest.length === 0) {
        return {
            "type": "AwaitExpression",
            "argument": call(expression, ...args)
        };
    }
    return rest.reduce(function(acc, item) {
        if (acc.type === 'CallExpression') {
            acc = {
                "type": "AwaitExpression",
                "argument": acc
            };
        }
        if (item[0] == "(") {
            return {
                "type": "AwaitExpression",
                "argument": call(acc, ...item[1])
            };
        } else {
            let result = {
                "type": "MemberExpression",
                "object": acc,
                property: item
            };
            if (item[0] == "[") {
                result.computed = true;
                result.property = item[2];
            }
            return result;
        }
    }, call(expression, ...args))
}

function_definition = _ "def" _ name:variable _ "(" args:(param_list / null_array) ")" _  body:statements _ "end" _ {
    const fn_name = name.name.replace(/\$_/, '');
    if (available_commands.includes(fn_name)) {
        const error = new Error(`invalid function name, '${fn_name}' is a command`);
        error.location = move_location(location(), 4, fn_name.length + 4);
        throw error;
    }
    return {
        "type": "FunctionDeclaration",
        "id": name,
        "params": args,
        "async": true,
        "body": {
            "type": "BlockStatement",
            "body": body
        }
    };
}

null_array = '' { return []; }

lambda = "lambda" _ "(" params:(param_list / null_array) ")" _ body:statements _ "end" _ {
    return lambda(params, body);
}

return = _ "return" _ expression:expression_like _ {
    return {
        "type": "ReturnStatement",
        "argument": expression
    };
}

var = _ "let" _ name:(variable) _ rest:("=" _ expression_like)? _ {
    return {
        "type": "VariableDeclaration",
        "declarations": [{
            "type": "VariableDeclarator",
            "id": name,
            "init": rest && rest[2]
        }],
        "kind": "let"
    };
}

DoubleStringCharacter = !('"' / "\\") . / "\\" . { return text(); } // "

string = '"' DoubleStringCharacter*  '"' { // '
    try {
        return create_template_literal(parse_string(text()));
    } catch(e) {
        const error = new Error(`invalid string literal`);
        error.location = location();
        throw error;
    }
}

literal = value:(integer / boolean / null) {
   return {"type": "Literal", "value": value };
}

boolean = value:("true" / "false") {
    return value === "true";
}

null = "null" { return null; }

infinity = "infinity" {
    return make_identifier('Infinity');
}

asterisk_name = word:$([a-z]+ "*")

command_name = word:$([a-z]+ "*"?)

async_command_name = word:$[a-z]+

adapter_async_strings = word:$async_command_name &{ return async_commands.includes(word) } { return word; }

adapter_asterisk_strings = word:$asterisk_name &{ return async_commands.includes(word) } { return word; }

adapter_static_strings = word:command_name &{ return sync_commands.includes(word); } { return word; }

adapter_command = extra_commands_single / extra_commands / async_command / static_command

extra_single = word:asterisk_name &{ return extra_single.includes(word); } { return word; }

extra_commands_single = _ method:extra_single _ expr:(adapter_command / expression) _ {
    return  {
        "type": "AwaitExpression",
        "argument": gaiman_call(map_extra_method(method), expr)
    };
}

extra_commands = _ method:adapter_asterisk_strings _ expr:(adapter_command / expression) _ args:(
    ("," _ expression)+ / '' {
      error(`Command ${method} require at least two arguments`);
    }) _ {
    args = args.map(x => x[2]);
    if (!is_number_literal(args[0])) {
        error(`animation command ${method} require number as second argument`);
    }
    return  {
        "type": "AwaitExpression",
        "argument": gaiman_call(map_extra_method(method), expr, ...args)
    };
}


async_command = _ method:adapter_async_strings " " _ expr:(adapter_command / expression) _ args:("," _ expression _)* {
    return  {
        "type": "AwaitExpression",
        "argument": gaiman_call(method, expr, ...args.map(x => x[2]))
    };
}

static_command = _ method:adapter_static_strings _ expr:(adapter_command / expression) _ args:("," _ expression)* {
    return gaiman_call(map_extra_method(method), expr, ...args.map(x => x[2]));
}

match = expression:(match_var / prop_access / variable) _ "=~" _ re:re _ {
    return {
        "type": "SequenceExpression",
        "expressions": [
            {
                type: "AssignmentExpression",
                operator: "=",
                left: match_identifer,
                right: call(
                    property(
                        call(make_identifier('String'), expression),
                        match_method
                    ),
                    re
                )
             },
             bang_bang(match_identifer)
         ]
    };
}

re = "/" re:([^/] / "\\\\/")* "/" flags:[igsu]* {
    return {
        type: "Literal",
        value: {},
        regex: {
            pattern: re.join(''),
            flags: flags ? flags.join('') : ''
        }
    }
}

math_expression = unary / or

not = "not" " " { return "!"; }

unary = op:("-" / "+" / not) _ expression:or {
    return {
        "type": "UnaryExpression",
        "operator": op,
        "argument": expression
    };
}

or
  = head:and tail:(SP "or" SP and)* {
      return logical_fold(head, tail, {"or": "||"});
  }

and
  = head:equal tail:(SP "and" SP equal)* {
      return logical_fold(head, tail, {"and": "&&"});
  }

equal
  = head:binary tail:(_ ("==" / "!=") _ binary)* {
      return binary_fold(head, tail, {"==": "===", "!=": "!=="});
    }

binary
  = head:plus_minus tail:(_ ("<=" / ">=" / "<" / ">") _ plus_minus)* {
      return binary_fold(head, tail);
    }

plus_minus
  = head:mul_div tail:(_ ("+" / "-") _ mul_div)* {
      return binary_fold(head, tail);
    }

mul_div
  = head:factor tail:(_ ("*" / "/" / "%") _ factor)* {
      return binary_fold(head, tail);
    }

factor
  = function_call / prop_access / string / literal / match_var / infinity / variable
  / "(" _ expr:(adapter_command / expression) _ ")" { return expr; }

any_name = variable:name {
  return make_identifier(variable_prefix + variable);
}

scoped = !keyword variable:name &{ return !available_commands.includes(variable) } {
  return make_identifier(variable_prefix + variable);
}

global = !keyword variable:("cookie" / "location" / "JSON" / "console" / "argv" / "node") {
    return make_identifier(variable);
}

variable = global / scoped

set = set_cookie / set_local

set_cookie = "cookie." name:name _ "=" _ expr:expression {
    return {
        "type": "AssignmentExpression",
        "operator": "=",
        "left": property(
            make_identifier('document'),
            make_identifier('cookie')
        ),
        "right": {
            "type": "BinaryExpression",
            "operator": "+",
            "left": {
                "type": "Literal",
                "value": name + "="
            },
            "right": call(make_identifier('String'), expr)
        }
    };
}

assign_operator = $("=" !"=" / "*=" / "+=" / "-=" / "%=" / "/=")


set_local = left:(prop_access / scoped) _ operator:assign_operator _  right:(expression_like / variable) {
    return {
        "type": "AssignmentExpression",
        "operator": operator,
        "left": left,
        "right": right
    };
}

match_var = "$" num:integer {
    return {
        type: "MemberExpression",
        computed: true,
        object: match_identifer,
        property: {
            type: "Literal",
            value: num
        }
    };
}

heredoc = "<<<" beginMarker "\n" text:content endMarker {
    const loc = location();
    const min = loc.start.column - 1;
    const re = new RegExp(`^ {${min}}`, 'mg');
    return {
        type: 'Literal',
        value: text.replace(re, '')
    };
}

__ = (![ \n),] .)

marker 'Marker' = $__+

beginMarker = m:marker { heredoc_begin = m; }

endMarker = "\n" " "* end:marker &{ return heredoc_begin === end; }

content = $(!endMarker .)*

comment = "#" [^\n]* { return null; }

integer = [0-9]+ { return parseInt(text(), 10); }

keyword = ("if" / "then" / "end" / "else" / "return" / "def" / "do" / "in" / "for" / "while" / "break" / "continue" / "lambda") !name

name = [A-Z_$a-z][A-Z_a-z0-9]* { return text(); }

WP = [ \t\n\r]

_ "optional whitespace"
  = (WP* comment)+ / WP* { return []; }

SP "whitespace"
  = WP+
